version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:30"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:30"
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
