version: 2

env_files:
  github_token: ~/.GH_TOKEN.txt

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: nonf
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - freebsd_amd64
      - openbsd_amd64
      - netbsd_amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: linux
    goos:
      - linux
    goarch:
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: nf
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

release:
  github:
    owner: semihalev
    name: sdns
  prerelease: false
  draft: true

archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}_sha256sums.txt'
  algorithm: sha256

changelog:
  disable: true

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}'
    builds:
      - nf
    homepage:  https://sdns.dev
    description: A high-performance, recursive DNS resolver server with DNSSEC support, focused on preserving privacy
    maintainer: Yasar Alev <semihalev@gmail.com>
    license: MIT
    bindir: /usr/bin
    contents:
      - src: "./contrib/linux/sdns.service"
        dst: "/lib/systemd/system/sdns.service"
      - src: "./contrib/linux/sdns.conf"
        dst: "/etc/sdns.conf"
        type: config
      - dst: "/var/lib/sdns"
        type: dir
    scripts:
      postinstall: "contrib/linux/adduser.sh"
    release: 1
    formats:
    - deb
    - rpm
    overrides:
      deb:
        dependencies:
          - systemd-sysv
      rpm:
        dependencies:
          - systemd

brews:
  -
    repository:
      owner: semihalev
      name: homebrew-tap
    directory: Formula
    homepage:  https://sdns.dev
    description: A high-performance, recursive DNS resolver server with DNSSEC support, focused on preserving privacy
    dependencies:
      - name: go
        type: build
    commit_author:
      name: semihalev
      email: semihalev@gmail.com
    service: |
      run [opt_bin/"sdns", "-config", etc/"sdns.conf"]
      keep_alive true
      require_root true
      error_log_path var/"log/sdns.log"
      log_path var/"log/sdns.log"
      working_dir opt_prefix
    test: |
      fork do
        exec bin/"sdns", "-config", testpath/"sdns.conf"
      end
      sleep(2)
      assert_predicate testpath/"sdns.conf", :exist?
