// Code generated by gen.go DO NOT EDIT.

package main

import (
	_ "github.com/semihalev/sdns/middleware/recovery"
	_ "github.com/semihalev/sdns/middleware/metrics"
	_ "github.com/semihalev/sdns/middleware/accesslist"
	_ "github.com/semihalev/sdns/middleware/ratelimit"
	_ "github.com/semihalev/sdns/middleware/edns"
	_ "github.com/semihalev/sdns/middleware/accesslog"
	_ "github.com/semihalev/sdns/middleware/chaos"
	_ "github.com/semihalev/sdns/middleware/hostsfile"
	_ "github.com/semihalev/sdns/middleware/blocklist"
	_ "github.com/semihalev/sdns/middleware/as112"
	_ "github.com/semihalev/sdns/middleware/cache"
	_ "github.com/semihalev/sdns/middleware/failover"
	_ "github.com/semihalev/sdns/middleware/resolver"
	_ "github.com/semihalev/sdns/middleware/forwarder"
)