// Code generated by gen.go DO NOT EDIT.

// Package defaults holds SDNS's default middleware chain, in its default
// order.
//
// It is a package rather than an init in main so that everything which
// needs the real chain can ask for it: the binary, the benchmarks, a
// harness. When this lived in main it could not be imported, so each of
// those kept a list of its own, and they drifted, which is worse than
// duplication because a benchmark that quietly measures five handlers
// fewer than production still reports a number.
package defaults

import (
	"github.com/semihalev/sdns/config"
	"github.com/semihalev/sdns/middleware"

	"github.com/semihalev/sdns/middleware/accesslist"
	"github.com/semihalev/sdns/middleware/accesslog"
	"github.com/semihalev/sdns/middleware/as112"
	"github.com/semihalev/sdns/middleware/blocklist"
	"github.com/semihalev/sdns/middleware/cache"
	"github.com/semihalev/sdns/middleware/chaos"
	"github.com/semihalev/sdns/middleware/dns64"
	"github.com/semihalev/sdns/middleware/dnstap"
	"github.com/semihalev/sdns/middleware/edns"
	"github.com/semihalev/sdns/middleware/failover"
	"github.com/semihalev/sdns/middleware/forwarder"
	"github.com/semihalev/sdns/middleware/hostsfile"
	"github.com/semihalev/sdns/middleware/kubernetes"
	"github.com/semihalev/sdns/middleware/metrics"
	"github.com/semihalev/sdns/middleware/ratelimit"
	"github.com/semihalev/sdns/middleware/recovery"
	"github.com/semihalev/sdns/middleware/reflex"
	"github.com/semihalev/sdns/middleware/resolver"
	"github.com/semihalev/sdns/middleware/rpz"
	"github.com/semihalev/sdns/middleware/views"
)

type entry struct {
	name string
	ctor middleware.Constructor
}

var chain = []entry{
	{"recovery", func(cfg *config.Config) middleware.Handler { return recovery.New(cfg) }},
	{"metrics", func(cfg *config.Config) middleware.Handler { return metrics.New(cfg) }},
	{"dnstap", func(cfg *config.Config) middleware.Handler { return dnstap.New(cfg) }},
	{"accesslist", func(cfg *config.Config) middleware.Handler { return accesslist.New(cfg) }},
	{"ratelimit", func(cfg *config.Config) middleware.Handler { return ratelimit.New(cfg) }},
	{"reflex", func(cfg *config.Config) middleware.Handler { return reflex.New(cfg) }},
	{"edns", func(cfg *config.Config) middleware.Handler { return edns.New(cfg) }},
	{"accesslog", func(cfg *config.Config) middleware.Handler { return accesslog.New(cfg) }},
	{"chaos", func(cfg *config.Config) middleware.Handler { return chaos.New(cfg) }},
	{"hostsfile", func(cfg *config.Config) middleware.Handler { return hostsfile.New(cfg) }},
	{"views", func(cfg *config.Config) middleware.Handler { return views.New(cfg) }},
	{"blocklist", func(cfg *config.Config) middleware.Handler { return blocklist.New(cfg) }},
	{"rpz", func(cfg *config.Config) middleware.Handler { return rpz.New(cfg) }},
	{"as112", func(cfg *config.Config) middleware.Handler { return as112.New(cfg) }},
	{"kubernetes", func(cfg *config.Config) middleware.Handler { return kubernetes.New(cfg) }},
	{"dns64", func(cfg *config.Config) middleware.Handler { return dns64.New(cfg) }},
	{"cache", func(cfg *config.Config) middleware.Handler { return cache.New(cfg) }},
	{"failover", func(cfg *config.Config) middleware.Handler { return failover.New(cfg) }},
	{"resolver", func(cfg *config.Config) middleware.Handler { return resolver.New(cfg) }},
	{"forwarder", func(cfg *config.Config) middleware.Handler { return forwarder.New(cfg) }},
}

// Register registers the default chain, in order.
func Register() { RegisterUpTo("") }

// RegisterUpTo registers the chain up to but not including name; an empty
// name registers all of it.
//
// It exists for the harnesses that replace the tail, a benchmark
// standing a stub in for the resolver, so that what runs ahead of the
// stub is the real chain rather than a hand-kept approximation of it.
func RegisterUpTo(stop string) {
	for _, e := range chain {
		if e.name == stop {
			return
		}
		middleware.Register(e.name, e.ctor)
	}
}
