name: sdns
adopt-info: sdns
summary: A DNS Resolver Server.
description: |
  A high-performance, recursive DNS resolver server with DNSSEC support, focused on preserving privacy.

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: strict
base: core18

parts:
  sdns:
    plugin: go
    source: https://github.com/semihalev/sdns.git
    go-importpath: github.com/semihalev/sdns
    source-type: git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info sdns | awk '$1 == "latest/stable:" { print $2 }')"
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      snapcraftctl set-grade stable
    stage:
     - bin/sdns
apps:
  sdns:
    command: sdns
    plugs: [network-bind]
    daemon: simple
