name: Snap Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.5.3)'
        required: true
        type: string

jobs:
  snap-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # For manual dispatch, use main branch but checkout the tag for version
          ref: ${{ github.event_name == 'workflow_dispatch' && 'main' || github.ref }}

      - name: Set version from tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.tag }} -- sdns.go
          
      - name: Build snap
        uses: snapcore/action-build@v1
        id: build

      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable